name: Generate Graphs

on:
  workflow_dispatch:
    inputs:
      type_solving:
            description: 'Type of solving method (hexaly / simulatedAnnealing)'
            required: true
            default: 'simulatedAnnealing'
            type: string

jobs:
  generate-graphs:
    runs-on: ubuntu-latest

    permissions:
      contents: write     # REQUIRED to push back to the repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # needed so git can push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run script
        run: |
          cd ${{ github.event.inputs.type_solving }}
          python generateGraphs.py
        # change to your actual script name

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git pull origin main
          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update from GitHub Actions, instances run"
            git push
          fi
