name: Run all instances

on:
  workflow_dispatch:
    inputs:
        type_solving:
          description: 'Type of solving method (hexaly / simulatedAnnealing)'
          required: true
          default: 'simulatedAnnealing'
          type: choice
          options:
            - 'hexaly'
            - 'simulatedAnnealing'
        is_extended:
            description: 'Whether to generate extended instances (yes / no)'
            required: true
            default: 'no'
            type: choice
            options:
              - 'yes'
              - 'no'

jobs:
  run-all-instances:
    runs-on: ubuntu-latest

    permissions:
      contents: write     # REQUIRED to push back to the repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # needed so git can push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install hexaly -i https://pip.hexaly.com
      
      - name: Create Hexaly license file
        run: |
          sudo mkdir -p /opt/hexaly_14_0
          echo "$HEXALY_LICENSE" | sudo tee /opt/hexaly_14_0/license.dat > /dev/null
        env:
          HEXALY_LICENSE: ${{ secrets.HEXALY_LICENSE }}


      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
           
      - name: Run script
        run: |
          cd ${{ github.event.inputs.type_solving }}
          if [ "${{ github.event.inputs.is_extended }}" = "yes" ]; then
            python runAllInstancesExtended.py
          else
            python runAllInstances.py
          fi
        # change to your actual script name

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git pull origin main
          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update from GitHub Actions, instances run"
            git push
          fi
